---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
      - id: seed-isort-config
        args: ['--exclude=(docs?|examples?|tests?|utils?)/.*\.py']
...
